[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
frontend = { path = "../frontend" }
backend = { path = "../backend" }
wasm-bindgen = "0.2.92"
wasmprinter = "0.206.0"
console_error_panic_hook = "0.1.7"
