[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ariadne = "0.4.0"
yansi = "0.5.1"
logos = "0.14.0"
num-derive = "0.4.2"
num-traits = "0.2.18"
rowan = "0.15.15"
lazy_static = "1.4.0"
backend = { path = "../backend" }
text-size = "1.1.1"
line-index = "0.1.1"

[dev-dependencies]
insta = { version = "1.34.0", features = ["glob"] }
