[package]
name = "backend"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
text-size = "1.1.1"
wasm-encoder = "0.209"
frontend = { path = "../frontend" }
tracing = { version = "0.1.40", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
