[package]
name = "backend"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
text-size = "1.1.1"
wasm-encoder = "0.209"
frontend = { path = "../frontend" }

[dev-dependencies]
insta = { version = "1.34.0", features = ["glob"] }
insta-cmd = "0.6.0"
