[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nemo"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
backend = { path = "../backend" }
frontend = { path = "../frontend" }
playground = { path = "../playground" }
language-server = { path = "../language-server" }
